org.gradle.parallel=true
org.gradle.caching=true
kotlin.code.style=official
android.useAndroidX=true
android.suppressUnsupportedCompileSdk=37.0
version=1.26.1
ksp.useKSP2=true
org.gradle.java.installations.paths=E:\\Java\\hw-jdk-11.0.2,E:\\Java\\microsoft-jdk-17.0.20+8,E:\\Java\\microsoft-jdk-25.0.4+7
